spring.application.name=monetra-backend

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

logging.level.org.hibernate.SQL=warn
jwt.expiration=86400000