spring.application.name=monetra-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fqtpjgzbjkkfxzcuetxy
spring.datasource.password=Alisonswift1989<3

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Y2hhbmdlX3RoaXNfdG9fc2VjdXJlX3JhbmRvbV9rZXk
jwt.expiration=86400000